import Foundation

struct ReflectionQuestions {
    static let all = [
        "What is bothering you right now?",
        "What are you overthinking?",
        "What are you afraid to say out loud?",
        "What is one thing you wish people understood about you?",
        "What was the hardest part of your day?",
        "Is there a conversation you're avoiding? Why?",
        "What do you need to forgive yourself for?",
        "What is a secret you're tired of keeping?",
        "When did you last feel truly seen?",
        "What are you holding onto that no longer serves you?",
        "What is your biggest regret from this past week?",
        "What part of your future scares you the most?",
        "If you could change one decision you made, what would it be?",
        "What does \"peace\" feel like to you right now?",
        "Who do you miss, even if they're still in your life?",
        "What is a \"what if\" that keeps you up at night?",
        "What are you forcing yourself to do that you hate?",
        "What is the kindest thing you haven't said to someone yet?",
        "What are you mourning right now?",
        "What is a dream you've given up on?",
        "What makes you feel small?",
        "When do you feel most alone?",
        "What mask are you wearing today?",
        "What is a truth you're running away from?",
        "What is the one thing you're most proud of today?",
        "What do you wish you could say to your younger self?",
        "What is a burden you're tired of carrying?",
        "What does your inner critic keep telling you?",
        "What is something you've never told anyone?",
        "What are you most grateful for in this moment?",
        "What is a fear you're ready to let go of?",
        "What is a habit you're trying to break?",
        "What is a boundary you need to set?",
        "What is a question you're afraid to ask?",
        "What is a lesson you've learned recently?",
        "What is a memory that still brings you pain?",
        "What is a hope you're afraid to share?",
        "What is a part of yourself you're still learning to love?",
        "What is a regret you're still carrying?",
        "What is a need you're not expressing?",
        "What is a desire you're suppressing?",
        "What is a feeling you're avoiding?",
        "What is a thought you're judging?",
        "What is a belief that is limiting you?",
        "What is a pattern you're noticing in your life?",
        "What is a choice you're struggling to make?",
        "What is a change you're resisting?",
        "What is a truth you're finally accepting?",
        "What is a dream you're finally chasing?",
        "What is a part of your life that feels out of alignment?"
    ]
}
